components:
  - name: mountain_1
    stand_x: 6
    stand_y: 6
  - name: c_tree_1
    stand_x: 4
    stand_y: 8
  - name: d_tree_1
    stand_x: 4
    stand_y: 8
  - name: dead_tree_1
    stand_x: 5
    stand_y: 7
  - name: sea_border_s
    tile_x: 20
    tile_y: -13
  - name: sea_border_sw
    tile_x: 35
    tile_y: 1
  - name: sea_border_nw
    tile_x: 35
    tile_y: 16
  - name: shore_out_sw
    tile_x: 28
    tile_y: 23
  - name: shore_out_se
    tile_x: -1
    tile_y: 23
  - name: shore_out_e
    tile_x: 27
    tile_y: -5
  - name: shore_out_ne
    tile_x: -1
    tile_y: -12
  - name: shore_out_nw
    tile_x: 28
    tile_y: -12
  - name: shore_out_w
    tile_x: -18
    tile_y: -5
  - name: shore_in_sw
    tile_x: 27
    tile_y: -5
  - name: shore_in_se
    tile_x: -1
    tile_y: -5
  - name: shore_in_e
    tile_x: -27
    tile_y: 8
  - name: shore_in_w
    tile_x: 34
    tile_y: 8
  - name: shore_in_ne
    tile_x: -2
    tile_y: 16
  - name: shore_in_nw
    tile_x: 27
    tile_y: 16
