components:
  - name: mountain_1
    stand_x: 6
    stand_y: 6
  - name: c_tree_1
    stand_x: 4
    stand_y: 8
  - name: d_tree_1
    stand_x: 4
    stand_y: 8
  - name: dead_tree_1
    stand_x: 5
    stand_y: 7
  - name: sea_border_s
    tile_x: 20
    tile_y: -13
  - name: sea_border_sw
    tile_x: 35
    tile_y: 1
  - name: sea_border_nw
    tile_x: 35
    tile_y: 16
