animations:
- name: sea_0
  stages:
  - {component_name: sea_00_00, duration: 0.2}
  - {component_name: sea_00_01, duration: 0.2}
  - {component_name: sea_00_02, duration: 0.2}
  - {component_name: sea_00_03, duration: 0.2}
  - {component_name: sea_00_04, duration: 0.2}
  - {component_name: sea_00_05, duration: 0.2}
  - {component_name: sea_00_06, duration: 0.2}
  - {component_name: sea_00_07, duration: 0.2}
  - {component_name: sea_00_08, duration: 0.2}
  - {component_name: sea_00_09, duration: 0.2}
- name: sea_1
  stages:
  - {component_name: sea_01_00, duration: 0.2}
  - {component_name: sea_01_01, duration: 0.2}
  - {component_name: sea_01_02, duration: 0.2}
  - {component_name: sea_01_03, duration: 0.2}
  - {component_name: sea_01_04, duration: 0.2}
  - {component_name: sea_01_05, duration: 0.2}
  - {component_name: sea_01_06, duration: 0.2}
  - {component_name: sea_01_07, duration: 0.2}
  - {component_name: sea_01_08, duration: 0.2}
  - {component_name: sea_01_09, duration: 0.2}
- name: sea_2
  stages:
  - {component_name: sea_02_00, duration: 0.2}
  - {component_name: sea_02_01, duration: 0.2}
  - {component_name: sea_02_02, duration: 0.2}
  - {component_name: sea_02_03, duration: 0.2}
  - {component_name: sea_02_04, duration: 0.2}
  - {component_name: sea_02_05, duration: 0.2}
  - {component_name: sea_02_06, duration: 0.2}
  - {component_name: sea_02_07, duration: 0.2}
  - {component_name: sea_02_08, duration: 0.2}
  - {component_name: sea_02_09, duration: 0.2}
- name: sea_3
  stages:
  - {component_name: sea_03_00, duration: 0.2}
  - {component_name: sea_03_01, duration: 0.2}
  - {component_name: sea_03_02, duration: 0.2}
  - {component_name: sea_03_03, duration: 0.2}
  - {component_name: sea_03_04, duration: 0.2}
  - {component_name: sea_03_05, duration: 0.2}
  - {component_name: sea_03_06, duration: 0.2}
  - {component_name: sea_03_07, duration: 0.2}
  - {component_name: sea_03_08, duration: 0.2}
  - {component_name: sea_03_09, duration: 0.2}
